Repository AY2223S1-CS2103T-T08-1/tp, pull requests merged in 2022-10, with the labels that each got.

#40 Fix config
  docs/_config.yml
Labels: severity.Low

#48 Name changes
  docs/UserGuide.md
  docs/index.md
Labels: priority.High

#53 Add Login page
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/hoodineee.md
  docs/team/jgyj123.md
  docs/team/joosxi.md
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/auth/AuthHandler.java
  src/main/java/seedu/address/auth/Credentials.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/LoginErrorWindow.java
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/Login.fxml
  src/main/resources/view/LoginErrorWindow.fxml
  src/test/java/seedu/address/auth/AuthHandlerTest.java
Labels: type.Story, priority.High

#59 Person model refactoring
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ClassContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Personality.java
  src/main/java/seedu/address/model/person/StudentClass.java
  src/main/java/seedu/address/model/person/Subject.java
  src/main/java/seedu/address/model/person/SubjectContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/subject/Attendance.java
  src/main/java/seedu/address/model/person/subject/Grade.java
  src/main/java/seedu/address/model/person/subject/Subject.java
  src/main/java/seedu/address/model/person/subject/SubjectHandler.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, severity.High

#64 Subject field changes
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/subject/Assessment.java
  src/main/java/seedu/address/model/person/subject/Attendance.java
  src/main/java/seedu/address/model/person/subject/Grade.java
  src/main/java/seedu/address/model/person/subject/Grades.java
  src/main/java/seedu/address/model/person/subject/Subject.java
  src/main/java/seedu/address/model/person/subject/SubjectHandler.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/subject/AssessmentTest.java
  src/test/java/seedu/address/model/person/subject/AttendanceTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, severity.High

#65 Defensive programming and other updates
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/subject/Attendance.java
  src/test/java/seedu/address/model/person/subject/AttendanceTest.java
Labels: priority.Medium

#68 Developer guide changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/e1010101.md
  docs/tutorials/AddRemark.md
Labels: priority.Low

#69 Add predictive algorithm
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/algorithm/PredictionUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/PredictionCommand.java
  src/main/java/seedu/address/logic/commands/StatisticsCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PredictionCommandParser.java
  src/main/java/seedu/address/model/person/FindCommandPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/subject/Assessment.java
  src/main/java/seedu/address/model/person/subject/Grades.java
  src/main/java/seedu/address/model/person/subject/Subject.java
  src/main/java/seedu/address/model/person/subject/SubjectHandler.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSubject.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PredictionWindow.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PredictionWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/algorithm/PredictionTest.java
  src/test/java/seedu/address/model/person/subject/AssessmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#82 Predictive algorithm 2
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/PredictionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PredictionWindow.java
  src/main/resources/view/PredictionWindow.css
  src/main/resources/view/PredictionWindow.fxml
Labels: priority.High

#83 Add fixes for Attendance field
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/subject/Subject.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#84 Fix json
  .gitignore
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/subject/Assessment.java
  src/main/java/seedu/address/model/person/subject/Grades.java
  src/main/java/seedu/address/model/person/subject/Subject.java
  src/main/java/seedu/address/model/person/subject/SubjectHandler.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSubject.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#85 Common fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: priority.High

#103 Find command fixes
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/FindCommandPredicate.java
  src/main/java/seedu/address/model/person/subject/SubjectHandler.java
Labels: priority.High

#105 Minor field fix
  src/main/java/seedu/watson/storage/JsonAdaptedPerson.java
Labels: priority.High

#91 Mark attendance command v1.3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/watson/logic/commands/AddCommand.java
  src/main/java/seedu/watson/logic/commands/EditCommand.java
  src/main/java/seedu/watson/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/watson/logic/parser/AddCommandParser.java
  src/main/java/seedu/watson/logic/parser/CliSyntax.java
  src/main/java/seedu/watson/logic/parser/DatabaseParser.java
  src/main/java/seedu/watson/logic/parser/EditCommandParser.java
  src/main/java/seedu/watson/logic/parser/FindCommandParser.java
  src/main/java/seedu/watson/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/watson/logic/parser/ParserUtil.java
  src/main/java/seedu/watson/model/Model.java
  src/main/java/seedu/watson/model/ModelManager.java
  src/main/java/seedu/watson/model/person/Attendance.java
  src/main/java/seedu/watson/model/person/IndexNumber.java
  src/main/java/seedu/watson/model/person/Person.java
  src/main/java/seedu/watson/model/person/StudentClass.java
  src/main/java/seedu/watson/model/util/SampleDataUtil.java
  src/main/java/seedu/watson/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableDatabaseTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableDatabaseTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableDatabaseTest/typicalPersonsAddressBook.json
  src/test/java/seedu/watson/logic/LogicManagerTest.java
  src/test/java/seedu/watson/logic/commands/AddCommandTest.java
  src/test/java/seedu/watson/logic/commands/CommandTestUtil.java
  src/test/java/seedu/watson/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/watson/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/watson/testutil/PersonBuilder.java
  src/test/java/seedu/watson/testutil/PersonUtil.java
  src/test/java/seedu/watson/testutil/TypicalPersons.java
Labels: priority.High

#112 Minor fixes
  docs/_config.yml
  src/main/java/seedu/watson/logic/commands/GradeCommand.java
Labels: priority.High

#113 Index number fix
  build.gradle
  src/main/java/seedu/watson/ui/PersonCard.java
Labels: priority.High

#115 Checkstyle fixes
  src/main/java/seedu/watson/logic/commands/GradeCommand.java
  src/main/java/seedu/watson/ui/GradeWindow.java
Labels: priority.High

#116 User guide dev guide update
  docs/UserGuide.md
Labels: priority.High

#117 Update User Guide images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/gui.png
  src/main/java/seedu/watson/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/book.png
  src/test/java/seedu/watson/commons/util/AppUtilTest.java
Labels: priority.High

#118 Read me changes
  README.md
Labels: priority.High

#185 Fix fxml
  src/main/java/seedu/watson/ui/StudentListPanel.java
  src/main/resources/view/StudentListPanel.fxml
Labels: priority.High

#186 Storage fixes
  src/main/java/seedu/watson/MainApp.java
  src/main/java/seedu/watson/model/tag/Tag.java
  src/main/java/seedu/watson/model/util/SampleDataUtil.java
  src/main/java/seedu/watson/storage/JsonDatabaseStorage.java
  src/main/java/seedu/watson/storage/StorageManager.java
  src/test/java/seedu/watson/logic/commands/CommandTestUtil.java
  src/test/java/seedu/watson/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/watson/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/watson/storage/JsonDatabaseStorageTest.java
Labels: priority.High

#188 Command fixes
  src/main/java/seedu/watson/logic/commands/AddCommand.java
  src/main/java/seedu/watson/logic/commands/AttendanceCommand.java
  src/main/java/seedu/watson/logic/commands/EditCommand.java
  src/main/java/seedu/watson/logic/commands/FindCommand.java
  src/main/java/seedu/watson/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/watson/logic/commands/PredictionCommand.java
  src/main/java/seedu/watson/logic/commands/RemarkCommand.java
  src/main/java/seedu/watson/logic/parser/AddCommandParser.java
  src/main/java/seedu/watson/logic/parser/AttendanceCommandParser.java
  src/main/java/seedu/watson/logic/parser/CliSyntax.java
  src/main/java/seedu/watson/logic/parser/DatabaseParser.java
  src/main/java/seedu/watson/logic/parser/EditCommandParser.java
  src/main/java/seedu/watson/logic/parser/FindCommandParser.java
  src/main/java/seedu/watson/logic/parser/ParserUtil.java
  src/main/java/seedu/watson/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/watson/model/Model.java
  src/main/java/seedu/watson/model/ModelManager.java
  src/main/java/seedu/watson/model/student/Attendance.java
  src/main/java/seedu/watson/model/student/IndexNumber.java
  src/main/java/seedu/watson/model/student/Name.java
  src/main/java/seedu/watson/model/student/Student.java
  src/main/java/seedu/watson/model/util/SampleDataUtil.java
  src/main/java/seedu/watson/storage/JsonAdaptedStudent.java
  src/main/java/seedu/watson/ui/StudentCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableDatabaseTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableDatabaseTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableDatabaseTest/typicalStudentsAddressBook.json
  src/test/java/seedu/watson/logic/LogicManagerTest.java
  src/test/java/seedu/watson/logic/commands/AddCommandTest.java
  src/test/java/seedu/watson/logic/commands/CommandTestUtil.java
  src/test/java/seedu/watson/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/watson/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/watson/testutil/StudentBuilder.java
  src/test/java/seedu/watson/testutil/StudentUtil.java
  src/test/java/seedu/watson/testutil/TypicalStudents.java
Labels: priority.High

#193 More fixes
  src/main/java/seedu/watson/logic/commands/FindNameCommand.java
  src/main/java/seedu/watson/logic/commands/FindSubjectCommand.java
  src/main/java/seedu/watson/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/watson/logic/parser/DatabaseParser.java
  src/main/java/seedu/watson/logic/parser/FindCommandParser.java
  src/main/java/seedu/watson/logic/parser/FindNameCommandParser.java
  src/main/java/seedu/watson/logic/parser/FindSubjectCommandParser.java
  src/main/java/seedu/watson/model/student/Attendance.java
  src/main/java/seedu/watson/model/student/FindCommandPredicate.java
  src/test/java/seedu/watson/logic/commands/FindCommandTest.java
  src/test/java/seedu/watson/logic/parser/DatabaseParserTest.java
  src/test/java/seedu/watson/logic/parser/FindCommandParserTest.java
Labels: priority.High
